Fix tektonconfig patch
openshift-pipelines/pipeline-service pull request #186
Opened 2022-08-09 12:03 UTC by avinal

- add job to patch the tektonconfig

Signed-off-by: Avinal Kumar <avinal@redhat.com>

2022-08-09 12:07 UTC, avinal commented
The URL is still pointed to my branch for testing purposes, once it is tested to work I will revert them.

2022-08-09 12:24 UTC, fgiloux requested changes
I am concerned with the approach.
If we cannot have a change to a simple resource applied after it has been created we can as well get rid of Argo CD.

2022-08-09 12:24 UTC, fgiloux commented on gitops/argocd/tektoncd/patch-tekton-config.yaml
> +        - image: registry.redhat.io/openshift4/ose-cli:v4.9
The image should be 4.10

2022-08-09 12:24 UTC, fgiloux commented on gitops/argocd/tektoncd/patch-tekton-config.yaml
> +              oc patch TektonConfig config --type='json' -p='[{"op":"remove","path":"/spec/pruner/keep"},{"op":"add","path":"/spec/pruner/keep-since","value":2880},{"op":"replace","path":"/spec/prune
This is imperative. We don't need Argo CD if we patch in an imperative way one of the few config files we have

2022-08-09 12:32 UTC, fgiloux commented
@avinal As a side note: It should be possible to have a GitOps repository with overlays for testing that overwrite the required URLs so that they are pointing to your repository where required. In this way you can test your change without the need to change the URL in the resources. The scripts accept parameters.
If it does not work let us know as it would be something that we need to fix.

2022-08-30 23:37 UTC, xinredhat commented
/retest

2022-09-08 08:30 UTC, avinal commented
Closing in favor of #229

2022-09-08 08:30 UTC, closed without merging