refactor: Create 'architect' folder
openshift-pipelines/pipeline-service pull request #315
Opened 2022-10-21 15:08 UTC by Roming22

This commit is part of a larger set of commits with the goal of restructuring the repository.

Signed-off-by: Romain Arnaud <rarnaud@redhat.com>

2022-10-25 17:09 UTC, Mo3m3n requested changes
For each renamed/moved file or image we need to double check that it is not referenced elsewhere and update the reference.
Example: `docs/images/phase1.png` was moved to architect folder which broke the links in:
- ./README.md
- gitops/README.md
- architect/phase1.md

2022-10-25 17:33 UTC, Roming22 commented
> For each renamed/moved file or image we need to double check that it is not referenced elsewhere and update the reference. 

Done. Hopefully I did not miss any, but I fully expect that after moving everything around, there will be a few follow-up PRs to fine tune everything.

2022-10-26 06:17 UTC, bnallapeta commented on README.md
>  ### Running in Kubernetes or OpenShift
The content under this section says
You can deploy this PoC to your Kubernetes cluster with the `build.sh` and `run.sh` scripts in `ckcp` folder.
Please update this to 
You can setup Pipeline Service on your OpenShift cluster with the `openshift_dev_setup.sh` script in `ckcp` folder.

2022-10-26 12:02 UTC, Roming22 commented on README.md
>  ### Running in Kubernetes or OpenShift
Done

2022-10-26 12:41 UTC, merged