Fix and enable tekton-chains test in CI
openshift-pipelines/pipeline-service pull request #423
Opened 2023-01-03 10:03 UTC by Mo3m3n

When using runAsNonRoot we need one of the following:
- Use the `USER` directive in Dockerfile to specify a non root user
- use the `runAsUser` in kubernetes SecurityContext. 
In the case of tekton-chains test the used image does not specify a non root USER so `runAsUser` is required.

2023-01-03 10:52 UTC, ramessesii2 requested changes

2023-01-03 10:52 UTC, ramessesii2 commented on .tekton/pipeline-service-test.yaml
> +                KUBECONFIG=/kubeconfig CASES=pipelines, chains $TEST_DIR/test.sh
```suggestion
                KUBECONFIG=/kubeconfig CASES=pipelines,chains $TEST_DIR/test.sh
```
Ah, there is an extra space.

2023-01-03 11:11 UTC, Mo3m3n commented on .tekton/pipeline-service-test.yaml
> +                KUBECONFIG=/kubeconfig CASES=pipelines, chains $TEST_DIR/test.sh
Fixed

2023-01-03 12:50 UTC, Mo3m3n commented
CI is failing because of `tkn` not available. This is another reason to handle https://github.com/openshift-pipelines/pipeline-service/issues/421

2023-01-03 15:37 UTC, Roming22 commented
/retest

2023-01-03 16:43 UTC, Roming22 commented
/retest

2023-01-03 18:33 UTC, adambkaplan commented
I thought `runAsUser` presents issues for OpenShift. Does OpenShift 4.11 change the restricted SCC to allow non-zero `runAsUser` UIDs?

2023-01-03 18:36 UTC, Roming22 commented
/retest

2023-01-03 18:45 UTC, Mo3m3n commented
@adambkaplan 

>I thought runAsUser presents issues for OpenShift. Does OpenShift 4.11 change the restricted SCC to allow non-zero runAsUser UIDs?

That's usually the case yes,  maybe the issue does not happen here because the test is deploymed by the admin user directly (kubectl) rather than via a service account.

2023-01-03 19:18 UTC, gabemontero commented
> @adambkaplan
> 
> > I thought runAsUser presents issues for OpenShift. Does OpenShift 4.11 change the restricted SCC to allow non-zero runAsUser UIDs?
> 
> That's usually the case yes, maybe the issue does not happen here because the test is deploymed by the admin user directly (kubectl) rather than via a service account.

if you were creating a `Pod`, yes that would be the reason, but with a `PipelineRun` the tekton controller is the requesting user.  So the tekton controller's permissions are unioned with the permissions of the serviceaccount for the `PipelineRun` when `Pod` admission validation is ultimately performed.

2023-01-03 19:27 UTC, Roming22 commented
/retest

2023-01-03 20:34 UTC, Roming22 commented
/retest

2023-01-04 07:44 UTC, Roming22 commented
@Mo3m3n Rebasing against main should solve your CI issue.

2023-01-04 19:05 UTC, gabemontero commented
> > @adambkaplan
> > > I thought runAsUser presents issues for OpenShift. Does OpenShift 4.11 change the restricted SCC to allow non-zero runAsUser UIDs?
> > 
> > 
> > That's usually the case yes, maybe the issue does not happen here because the test is deploymed by the admin user directly (kubectl) rather than via a service account.
> 
> if you were creating a `Pod`, yes that would be the reason, but with a `PipelineRun` the tekton controller is the requesting user. So the tekton controller's permissions are unioned with the permissions of the serviceaccount for the `PipelineRun` when `Pod` admission validation is ultimately performed.

I was curious @adambkaplan and @Mo3m3n so a bit of a follow up:

- if you look at the tekton controller itself, it sets its runs as with `65532` per https://github.com/tektoncd/pipeline/blob/f9021b1385c0d5bfa4e61b9473597ca03d173cb6/config/controller.yaml#L134 and it is setting restricted profile per https://github.com/tektoncd/pipeline/blob/2ae8b6a54a1bab401dbd3b1cc533a3b087ca54ea/config/100-namespace/100-namespace.yaml#L22
- now, when you install on openshift, it still does its "random user ID" thing which has been around since the 3.x days ... a yaml snippet from a live tekton controller pod installed via the pipelines operator on my 4.11 cluster:

```
      runAsGroup: 65532
      runAsUser: 1000670000
```

but bottom line, I think you only get in trouble when the user is sufficiently low enough to move beyond restricted, and 65532 is "safe"

2023-01-06 11:43 UTC, Mo3m3n commented
closing this one in favor of https://github.com/openshift-pipelines/pipeline-service/pull/430

2023-01-06 11:43 UTC, closed without merging