[WIP] add helm to allow for helm based install of the minio operator
openshift-pipelines/pipeline-service pull request #451
Opened 2023-01-23 17:08 UTC by gabemontero

This is the enable install of the minio operator via `helm`

We are exploring that approach as a short (hopefully) workaround for the hypershift operator hub catalogs are out of date.  @adambkaplan is taking on pursuing that issue with the requisite teams separately.

See https://github.com/openshift-pipelines/pipeline-service/pull/443 for why this is a concern for getting minio in.

Next, marked as WIP for now given the conversation over in https://redhat-internal.slack.com/archives/C032EJ007C0/p1674487220868799 with @Roming22 and the infra team

Lastly, doing this in a separate PR than https://github.com/openshift-pipelines/pipeline-service/pull/443  since we have the issue where image update from a PR are not available in the PR.  The CI tests are currently hard coded to use the `main` tag of the images.

If / once this merges, I'll update #443 to use helm to install 4.5.8 of the minio operator.

2023-01-24 22:13 UTC, gabemontero commented
@Roming22 per the latest discourse in https://redhat-internal.slack.com/archives/C032EJ007C0/p1674487220868799  I think this is ready for any final reviews then merge.

2023-01-25 14:42 UTC, Roming22 requested changes

2023-01-25 14:42 UTC, Roming22 commented on ci/images/ci-runner/Dockerfile
> +#Installing helm as part of a work around for installing the minio operator while we sort out stale operator hub catalogs with hypershift.
This is not how we install software.
1. You need to pin a specific version in `shared/config/dependencies.sh`.
2. You need to add the command(s) to install the binary in `shared/hack/install`.
3. You need to add the binary to the `install.sh` command in the Dockerfile(s).

2023-01-26 14:13 UTC, gabemontero commented
ok - we had a chance to talk voice to voice and are decided, we are going with the older minio version, so no helm.

closing this out

2023-01-26 14:13 UTC, closed without merging