[FREEZE] add pipelines-scc
openshift-pipelines/pipeline-service pull request #643
Opened 2023-05-16 12:11 UTC by ramessesii2

Once we disable RBAC creation in Tekton-config, SCC will not be created automatically by Openshift-Pipelines operator.
Not sure how quickly we want this PR merged, since we're good for now.

2023-05-16 17:19 UTC, gabemontero requested changes
was able to compare with the `restricted` SCC on my 4.12 cluster

requests below thanks

2023-05-16 17:19 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +  - SETFCAP
put a comment that this is an addition from the `restricted` SCC

2023-05-16 17:19 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +  - system:cluster-admins
this is also an addition from the `restricted` SCC

From the godoc, this is just saying that cluster admins can use this SCC ... that is OK.

It is not saying that this SCC grants cluster-admin privs

https://github.com/openshift/api/blob/master/security/v1/types.go#L124-L127

2023-05-16 17:19 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +priority: 10
another addition from `restricted` SCC

2023-05-16 17:19 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +  - MKNOD
we are no longer dropping `KILL` , `SETUID`, and `SETGID` .... add a comment, and what was the need for that?

2023-05-16 17:19 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +  - SETFCAP
what was the need for this?  .... building images with buildah perhaps ?  whatever it is , clarify that in the comment

2023-05-16 18:00 UTC, gabemontero commented on operator/gitops/argocd/pipeline-service/openshift-pipelines/pipelines-scc.yaml
> +priority: 10
this affects the sort order for applying SCCS

this tells openshift to consider this SCC before the default SCCs

2023-05-17 05:33 UTC, ramessesii2 commented
Thanks @gabemontero for the review. In short, this `pipelines-scc` is the one generated by OSP itself and I've not altered anything. I'm happy to process your review comments though I just saw that @Roming22 has raised a [PR](https://github.com/openshift-pipelines/pipeline-service/pull/644/) which includes the changes [proposed here](https://github.com/openshift-pipelines/pipeline-service/pull/644/files#diff-ed2092bd3127355d7869e82f2975b63508b37fe17db779b6ef6339bb775b200a) as well.
@Roming22 do you want to take these reviews in considerations?

2023-05-17 12:50 UTC, Roming22 commented
We're on a bit of a time crunch re #644. If there is anything that is critical, let's fix it in #644, otherwise let's deal with the comments in a follow up PR.

2023-05-17 16:41 UTC, closed without merging