Pipeline Service troubleshooting Grafana Dashboard
openshift-pipelines/pipeline-service pull request #699
Opened 2023-06-28 07:05 UTC by ramessesii2

The following metrics are being queried:-
    * pipelinerun_duration_scheduled_seconds
      Using the expr - `sum by (namespace) ((avg_over_time(pipelinerun_duration_scheduled_seconds_sum[1h]) / avg_over_time(pipelinerun_duration_scheduled_seconds_count[1h])))`
      We calculate average scheduling duration per PipelineRun in seconds for each namespace over the last 1 hour
    * tekton_pipelines_controller_pipelinerun_duration_seconds
      Using the epxr - `sum by (namespace) ((avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_sum{status=\"success\"}[1h]) / avg_over_time(tekton_pipelines_controller_pipelinerun_duration_seconds_count{status=\"success\"}[1h])))`
      We calculate average duration of successful pipelineruns in seconds over one hour time window grouped by namespace.

#### Preview
![image](https://github.com/openshift-pipelines/pipeline-service/assets/54385449/5a649082-9817-4e71-88a5-7570d34289a2)

2023-06-28 07:10 UTC, ramessesii2 commented
As commented [ Grafana Observational graphs for Pipelines Controller Monitoring #683 ](https://github.com/openshift-pipelines/pipeline-service/pull/683#issuecomment-1610797812), I don't have the visibility if it's gonna look the same once we merge all of my PRs.
What we can do is go one by one over the PRs while merging. Once #683 is merged, I'll come over here again and rebase it.

2023-06-28 18:40 UTC, gabemontero requested changes
@ramessesii2 I think tekton_pipelines_controller_workqueue_depth should be included in this one as well.

A back log in the workqueue goes hand in hand IMO with troubleshooting you've got here for the time gap between creation and start.

Eventually, we'll want the throttled metrics on this panel too, but as those are not available until we can get to 1.11, I'm fine with those being done in a follow up PR.

2023-06-30 12:25 UTC, ramessesii2 commented
Hello @gabemontero,  I want to clarify `Pipeline Service troubleshooting` dashboard is meant to get the stats from individual namespace (if you look at the queries, they're ultimately grouped by ns) while `tekton_pipelines_controller_workqueue_depth` gathers data from core tekton reconciler. And additionally, I've already added  the workqueue_depth metric [here](https://github.com/openshift-pipelines/pipeline-service/pull/683/files#diff-13716f85d071b7d6b050dd4f5d738d85f4627f17f20ee8b68fd8f39084c72ce9R1445). Let me know your thoughts on this.

>  we'll want the throttled metrics on this panel too, 

Sure

2023-06-30 12:42 UTC, gabemontero commented
> Hello @gabemontero, I want to clarify `Pipeline Service troubleshooting` dashboard is meant to get the stats from individual namespace (if you look at the queries, they're ultimately grouped by ns) while `tekton_pipelines_controller_workqueue_depth` gathers data from core tekton reconciler. And additionally, I've already added the workqueue_depth metric [here](https://github.com/openshift-pipelines/pipeline-service/pull/683/files#diff-13716f85d071b7d6b050dd4f5d738d85f4627f17f20ee8b68fd8f39084c72ce9R1445). Let me know your thoughts on this.

Makes sense / works for me / thanks @ramessesii2 
> 
> > we'll want the throttled metrics on this panel too,
> 
> Sure

cool ... yeah we have the 1.11 bump passing in our test PRs.  @Roming22 will need to resolve with chains team how we deal with it long term in the continuation of https://github.com/openshift-pipelines/pipeline-service/pull/688 when he is back from PTO

2023-06-30 12:43 UTC, gabemontero commented
In which  order do you want to merge this PR vs. https://github.com/openshift-pipelines/pipeline-service/pull/683 ?

2023-07-03 06:51 UTC, ramessesii2 commented
I would like  683 to go first. Once that's done, I'll bump PipelineService SHA in infra for dev/stage. And will give this PR a rebase and will signal the merge.

2023-07-04 08:53 UTC, ramessesii2 commented
I've rebased this PR after merge of #683 & have confirmed it both on Staging & using Inner Loop Observability local setup. And it's ready to be merged.

2023-07-04 11:47 UTC, ramessesii2 commented
/test

2023-07-04 13:16 UTC, ramessesii2 commented
/retest pipeline-service-test

2023-07-06 12:51 UTC, Roming22 approved these changes

2023-07-06 12:51 UTC, merged